### ISSUE TITLE
Suggestion: make clear that instances calling Await are unsafe

### ISSUE THREAD

**Issue by dangerousben** [travisbrown/catbird#243]
There are a few uses of `Await` in typeclass instances provided by `util`: `Eq` and `Comonad` for `Future` and `Rerunnable`.

I suspect the `Eq` instances are only intended for testing, in which case they could just be moved into `test`.  I'm not sure what the Comonad instances are for at all - I can't envisage a use for them personally.

So my initial suggestion is:

- move the `Eq` instances into `test`
- move the `Comonad` instances into an `unsafe` or maybe `alleycats` subpackage with some docs to make it clear to the user what they're getting into (alternative option: just remove them)

I would be happy to do the gruntwork if a change is agreed on.

**Comment by travisbrown** [comment]
My reasoning here was that none of the `Eq` or `Comonad` instances are implicit (so I wouldn't even call them "instances" personally—I'd think of them more as helper methods), and if I remember correctly they all require an explicitly-provided duration.

So in order to put an `Await`-using instance into scope, you have to define your own implicit calling these methods, and to think about what duration you want to provide. In my view that's a high enough bar for intentionality—you definitely can shoot yourself in the foot, but you have to go through a couple of non-trivial steps to do it.

I'm not strongly opposed to moving them, but I do think they can be useful in situations where you just want to run some stuff in the REPL or a script, and I'd prefer just to add "unsafe" to the method names if there are concerns that they could be misused accidentally.

**Comment by dangerousben** [comment]
Makes sense.  How about some docs - I'll write some up with your suggested use cases if you like?

Out of curiosity, do you just use Comonad as a convenience for calling extract (once the instance is in scope), or do you do something more advanced with it?

**Comment by travisbrown** [comment]
@dangerousben I think I've also only used `Comonad` instances in tests (where it's sometimes practical for abstracting over contexts) or the REPL.
